version: "3.9"

services:
  server:
    build: /
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD:'root'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
    healthcheck:
      test: "/user/bin/mysql --user=root -password=root --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 60s
      retries: 10

volumes:
  my-db: